spring.application.name=seatunnel-orchestrator

server.port=8080

orchestration.etl-service-url=https://seatunnel-2-3-12-2.onrender.com
orchestration.etl-service-username=admin
orchestration.etl-service-password=admin

spring.data.mongodb.uri=mongodb+srv://amol64546:Z9sngTczeu8Gkczl@cluster1.rqus2ih.mongodb.net/orchestrator
