spring.application.name=SeaTunnel-Orchestrator

server.port=8081

orchestration.etl-service-url=http://localhost:8080
orchestration.etl-service-username=admin
orchestration.etl-service-password=admin

#orchestration.etl-service-url=https://seatunnel.gov-cloud.ai
#orchestration.etl-service-username=gaian
#orchestration.etl-service-password=GaianMobius

spring.data.mongodb.uri=mongodb://localhost:27017/orchestrator
