spring.application.name=seatunnel-orchestrator

server.port=8080

orchestration.etl-service-url=https://seatunnel-2-3-12-2.onrender.com
orchestration.etl-service-username=admin
orchestration.etl-service-password=admin
orchestration.username=admin
orchestration.password=admin
orchestration.jwt-secret=91f7f04821a7447cb6cbe875c4c9b605

spring.data.mongodb.uri=mongodb+srv://amol64546:Z9sngTczeu8Gkczl@cluster1.rqus2ih.mongodb.net/orchestrator
